language: cpp
compiler:
  - gcc
  - clang
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - g++-5
    - clang-3.6
    - valgrind
before_install:
 - cd /tmp
 - wget http://www.cmake.org/files/v3.3/cmake-3.3.1-Linux-x86_64.tar.gz
 - tar xzf cmake-3.3.1-Linux-x86_64.tar.gz
 - export PATH=/tmp/cmake-3.3.1-Linux-x86_64/bin:$PATH
 - cd -
before_script: mkdir build && cd build && if [ "${CXX}" = "clang++" ]; then export CXX=/usr/bin/clang++-3.6; fi && if [ "${CXX}" = "g++" ]; then export CXX=/usr/bin/g++-5; fi
script: cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_ESCRIPT_APPLICATION=ON -DBUILD_ESCRIPT_TEST=ON .. && make && ctest --verbose -D ExperimentalMemCheck

