env:
  global:
   - secure: "ddLIJLh3ehLuiwkmo91RYphfEa9WlVB01na3xzWmYgS7zLoURWnl+Kit9bRVbKUCDIUJgvO0R5G5wDWqO811N+LQ2F+NxGLU7xb5Enc5GRPUeSrzMAmX27hlCl8tea22lhUxuN6SGF7Ck3PnZ8F7yZq8xc778VY+roq+oJELtJE="
language: cpp
cache: apt
before_install:
 - sudo add-apt-repository --yes ppa:kalakris/cmake
 - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
 - sudo apt-get install -qq cmake g++-4.8 valgrind
 - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
before_script: mkdir build && cd build
script: /bin/true
addons:
  coverity_scan:
    project:
      name: "EScript/EScript"
      description: "Build submitted via Travis CI"
    notification_email: benjamin@eikel.org
    build_command_prepend: "cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_ESCRIPT_APPLICATION=ON -DBUILD_ESCRIPT_TEST=ON .."
    build_command: "make"
    branch_pattern: coverity_scan
