version: 1.0.{build}
branches:
  only:
  - 0.7.2.Egon_VisualStudioSupport
os: Visual Studio 2015
install:
- cmd: >-
    curl https://cmake.org/files/v3.3/cmake-3.3.2-win32-x86.zip --output cmake-3.3.2-win32-x86.zip

    7z x cmake-3.3.2-win32-x86.zip
before_build:
- cmd: >-
    mkdir build

    cd build

    ..\cmake-3.3.2-win32-x86\bin\cmake.exe -G "Visual Studio 14 2015" -DBUILD_ESCRIPT_APPLICATION=ON -DBUILD_ESCRIPT_TEST=ON ..
build:
  project: build\ALL_BUILD.vcxproj
  verbosity: normal
